----STUDENT----

CREATE TABLE STUDENT(
STUDENTNUMBER INT NOT NULL,
PASSWORD  VARCHAR(30) NOT NULL,
DOB       DATE,
SEX       VARCHAR(5) NOT NULL,
CURADD    VARCHAR(100) NOT NULL,
CURPHNO   LONGINT(10) NOT NULL,
PERMANENTADD    VARCHAR(100) NOT NULL,
PERMANENTPHNO   LONGINT(10) NOT NULL,
PRIMARY          KEY(STUDENTNUMBER)
);


---COLLEGE_INFO----

CREATE TABLE COLLEGEINFO(
SNO INT NOT NULL AUTO_INCREMENT,
COLLEGENAME     VARCHAR(50),
STARTYEAR       DATE,
ENDYEAR         DATE,
STUDNUMBER      INT NOT NULL,
COURSEID        INT NOT NULL,
DEGREEID        VARCHAR(10),
FOREIGN         KEY (STUDENTNUMBER) REFERENCES STUDENT(STUDENTNUMBER), 
FOREIGN         KEY (COURSEID) REFERENCES COURSESTAKEN(COURSEID),
FOREIGN         KEY (DEGREEID) REFERENCES DEGREE(DEGREEID),
PRIMARY         KEY(SNO)
);


---- DEGREE ----
CREATE TABLE DEGREE(
DESCRIPTION   TEXT,
DURATION      INT NOT NULL,
DEGREEID      INT NOT NULL,
PRIMARY       KEY(DEGREEID)
);



---COURSESTAKEN----

CREATE TABLE COURSESTAKEN(
COURSESCOMPLETED    INT NOT NULL,
GRADEEARNED         FLOAT NOT NULL,
CREDITHOURS         INT NOT NULL,
COURSESLEVEL        TEXT
);


----STUDENTCOURSES----
CREATE TABLE STUDENTCOURSE(
STUDENTNUMBER     INT NOT NULL,
COURSENUMBER      VARCHAR NOT NULL,
OFFERDEP          VARCHAR NOT NULL,
FOREIGN KEY       (STUDENTNUMBER) REFERENCES STUDENT(STUDENTNUMBER), 
FOREIGN KEY       (COURSENUMBER) REFERENCES COURSE(COURSENUMBER),
FOREIGN KEY       (OFFERDEP) REFERENCES COURSE(OFFERDEP)
);

--PERMANENTADDRESS--
CREATE TABLE PERMANENTADDRESS(
STUDENTNUMBER       VARCHAR(30),
FIRSTNAME           VARCHAR(40),
LASTNAME            VARCHAR(30),
CITY                VARCHAR(30),
STATE               VARCHAR(40),
ZIPCODE             VARCHAR(40),
FOREIGN KEY         (STUDENTNUMBER) REFERENCES STUDENT(STUDENTNUMBER)
);

--STUDENTDEPARTMENT--
CREATE TABLE STUDENTDEPARTMENT(
STUDENTNUMBER       VARCHAR(30),
TOTALSUB            INT NOT NULL,
CODE                VARCHAR(30),
FOREIGN             KEY (STUDENTNUMBER) REFERENCES STUDENT(STUDENTNUMBER),
FOREIGN             KEY (CODE) REFERENCES DEPARTMENT(CODE)
);

--DEPARTMENT--
CREATE TABLE DEPARTMENT(
CODE        VARCHAR(30),
NAME        VARCHAR(30),
SUBJECTS    INT NOT NULL,
COLLEGE     VARCHAR(30),
PRIMARY     KEY (CODE)
);

--GRADEREPORT--
CREATE TABLE GRADEREPORT(
LETTERGRADE     VARCHAR(20),
NUMERICGRADE    VARCHAR(20),
STUDENTNUMBER   VARCHAR(20),
SECTIONNUMBER   VARCHAR(20),
FOREIGN KEY     (STUDENTNUMBER) REFERENCES STUDENT(STUDENTNUMBER),
FOREIGN KEY     (SECTIONNUMBER) REFERENCES SECTION(SECTIONNUMBER),
);

--SECTION--
CREATE TABLE SECTION(
SECTIONNUMBER     INT NOT NULL,
COURSENUMBER      INT NOT NULL,
CODE              VARCHAR(30),
INSTRUCTOR        VARCHAR(20),
SEMESTER          VARCHAR(30),
YEAR              VARCHAR(30),
COURSE            VARCHAR(30),
PRIMARY KEY       (SEMESTER),
PRIMARY KEY       (YEAR),
FORIEGN KEY       (CODE) REFERENCES DEPARTMENT (CODE)
);

--COURSE--
CREATE TABLE COURSE(
COURSENUMBER         VARCHAR(30),
NAME                 VARCHAR(30),
DESCRIPTION          VARCHAR(30),
SEMESTERHOURS        VARCHAR(30),
COURSELEVEL          VARCHAR(30),
OFFERINGDEPARTMENT   VARCHAR(32),
FOREIGN KEY          (OFFERINGDEPARTMENT) REFERENCES STUDENTCOURSE(OFFERINGDEPARTMENT),
PRIMARY KEY          (COURSENUMBER)
);
